name: Use Hello World Action

on:
  pull_request:
    branches:
      - master

jobs:
  run-hello:
    runs-on: ubuntu-latest
    environment: int-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Dependency Tree
        id: dependency_tree_step
        run: |
          mvn -B dependency:tree -DoutputType=dot > source-dependency-tree.txt 2>&1

      - name: Upload Dependency Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-dependency-tree-output
          path: source-dependency-tree.txt
          retention-days: 1

      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Run Maven Dependency Tree
        id: master_dependency_tree_step
        run: |
          cd master
          mvn -B dependency:tree -DoutputType=dot > master-dependency-tree.txt 2>&1

      - name: Upload Master Dependency Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: master-dependency-tree-output
          path: master-dependency-tree.txt
          retention-days: 1

      - name: Run Hello World Action
        uses: koraytugay/hackaton@v1.0.11
        env:
          USERNAME: ${{ secrets.INT_TEST_USERNAME }}
          PASSWORD: ${{ secrets.INT_TEST_PASSWORD }}
